### ISSUE TITLE
소스코드 공개 요청

### ISSUE THREAD

**Issue by HyunWooZZ** [tmo-gg/war3-releases#1]
소스코드 공개 해주시면 유저들이 알아서 유지 보수할 수 있을 것 같습니다.
혹시 공개가 가능하실까요?
감사합니다.

**Comment by changmyeong** [comment]
안녕하세요. 소스코드 공개 괜찮을 것 같습니다.
상의해 보고 코멘트 드릴게요.

**Comment by min7544505** [comment]
지금까지 정말 잘 써왔습니다. 노고에 감사드립니다.
오늘 블리자드 리포지드가 업데이트 된 이후 연동이 안되는 것 같더라고요. 만약 공개해주시다면 코드나 프로그래밍은 잘 모르지만, 연구해서라도 연동시켜보고 싶습니다.
감사합니다.

**Comment by changmyeong** [comment]
공개에 1~2달이 소요될 것으로 보이고 웹/워3 클래식/워3 리포지드가 오픈될 예정입니다.
기존 프로그램 역시 오픈 후 따로 복원해서 배포될 예정인데, 기존 맵 외 다른 맵 역시 지원되도록 기여해 주실 수 있으실까요?

**Comment by min7544505** [comment]
안녕하세요.

공개요청에 답해주신 점 감사드립니다.
꾸준히 즐기고 있는 유저로서 도울 수 있는 부분은 최대한 돕도록 하겠습니다.

실력이 좀 부족하긴 하지만, 최대한 잘 찾아서 해보겠습니다!

감사합니다.

-----Original Message-----

**Comment by changmyeong** [comment]
> 안녕하세요. 공개요청에 답해주신 점 감사드립니다. 꾸준히 즐기고 있는 유저로서 도울 수 있는 부분은 최대한 돕도록 하겠습니다. 실력이 좀 부족하긴 하지만, 최대한 잘 찾아서 해보겠습니다! 감사합니다.
> […](#)
> -----Original Message----- From: ***@***.***> To: ***@***.***>; Cc: ***@***.***>; ***@***.***>; Sent: 2024-05-18 (토) 14:06:02 (GMT+09:00) Subject: Re: [tmo-gg/war3-releases] 소스코드 공개 요청 (Issue #1) 공개에 1~2달이 소요될 것으로 보이고 웹/워3 클래식/워3 리포지드가 오픈될 예정입니다. 기존 프로그램 역시 오픈 후 따로 복원해서 배포될 예정인데, 기존 맵 외 다른 맵 역시 지원되도록 기여해 주실 수 있으실까요? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

감사합니다 :) 공개 후 코멘트 다시 드리겠습니다.

**Comment by leehoegyu** [comment]
@HyunWooZZ 
@min7544505 
https://github.com/tmo-gg/War3Buddy
실행 파일 소스코드입니다.

**Comment by min7544505** [comment]
안녕하세요.

소스코드 공유해 주셔서 감사합니다.
프로그래밍은 잘 몰라서 프로그래밍 언어를 잘 아는 지인을 통해 시간날 때 한번 수정 해보고 공부해보겠습니다.

감사합니다.

-----Original Message-----
